/**
 * Types shared by the database -> Feishu Bitable synchronisation layer.
 *
 * The module deliberately does not import a Feishu or database SDK.  Database
 * adapters only need to return plain objects and the HTTP implementation can
 * be replaced in tests (or by a host application's HTTP client).
 */

export type DatabaseRow = Record<string, unknown>;
/** A page emitted by DatabaseAdapter.iterateRows. */
export type DatabaseRowPage = DatabaseRow[];
export type DatabaseRowsInput =
  | Iterable<DatabaseRow | DatabaseRowPage>
  | AsyncIterable<DatabaseRow | DatabaseRowPage>;

/** Values accepted by the Bitable records API after mapping. */
export type BitableFieldValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | BitableFieldValue[]
  | { [key: string]: unknown };

export type ValueTransformer = (
  value: unknown,
  row: DatabaseRow,
) => BitableFieldValue | Promise<BitableFieldValue>;

/** Built-in transforms suitable for JSON-based sync configurations. */
export type MappingTransformName = 'text' | 'number' | 'date' | 'boolean' | 'json' | 'auto';
export type MappingTransform = ValueTransformer | MappingTransformName;

/**
 * A source-to-target field mapping.
 *
 * `source` and `target` are the canonical names.  `sourceField` and
 * `targetField` are accepted aliases at runtime by the mapping helpers to
 * make configuration generated by different clients easy to consume.
 */
export interface FieldMapping {
  source: string;
  target: string;
  /** Optional value conversion (dates, enums, JSON, etc.). */
  transform?: MappingTransform;
  /** Alias for transform used by some configuration UIs. */
  formatter?: MappingTransform;
  /** Value used when the source is missing or undefined. */
  defaultValue?: BitableFieldValue;
  /** Omit a missing value instead of writing the default/null value. */
  omitIfEmpty?: boolean;
  /** Fail the row when this mapping has no source value. */
  required?: boolean;
}

export interface FieldMappingAlias {
  source?: string;
  target?: string;
  sourceField?: string;
  targetField?: string;
  transform?: MappingTransform;
  formatter?: MappingTransform;
  defaultValue?: BitableFieldValue;
  omitIfEmpty?: boolean;
  required?: boolean;
}

export type FieldMappingInput = FieldMapping | FieldMappingAlias;

export interface FeishuRecord {
  record_id?: string;
  recordId?: string;
  fields: Record<string, BitableFieldValue>;
  [key: string]: unknown;
}

export interface FeishuRecordPage {
  items: FeishuRecord[];
  hasMore: boolean;
  pageToken?: string;
  total?: number;
}

export interface RecordSearchOptions {
  pageSize?: number;
  pageToken?: string;
  filter?: string | Record<string, unknown>;
  fieldNames?: string[];
  sort?: unknown[];
  automaticFields?: boolean;
  signal?: AbortSignal;
}

export interface FeishuField {
  field_id?: string;
  field_name?: string;
  fieldId?: string;
  fieldName?: string;
  type?: number | string;
  property?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface FeishuTable {
  table_id?: string;
  table_name?: string;
  tableId?: string;
  tableName?: string;
  [key: string]: unknown;
}

export interface FeishuBatchResult {
  records: FeishuRecord[];
  /** Raw API response, useful when Feishu adds response fields. */
  raw?: unknown;
}

export interface FeishuCreateRecordInput {
  fields: Record<string, BitableFieldValue>;
  [key: string]: unknown;
}

export interface FeishuUpdateRecordInput {
  record_id?: string;
  recordId?: string;
  fields: Record<string, BitableFieldValue>;
  [key: string]: unknown;
}

export interface RetryOptions {
  /** Number of retries after the initial request. Defaults to 3. */
  maxRetries?: number;
  /** Initial exponential backoff delay in milliseconds. Defaults to 300. */
  initialDelayMs?: number;
  /** Upper bound for an individual delay. Defaults to 10 seconds. */
  maxDelayMs?: number;
  /** Exponential multiplier. Defaults to 2. */
  backoffFactor?: number;
  /** Add a small random fraction to avoid a thundering herd. Defaults to 0.1. */
  jitter?: number;
  /** Override sleeping in tests or hosts with their own scheduler. */
  sleep?: (milliseconds: number) => Promise<void>;
}

export interface FeishuClientOptions extends RetryOptions {
  /** Tenant/user access token. It is sent as `Bearer <token>`. */
  accessToken?: string;
  /** Alias accepted for callers that use tenantAccessToken terminology. */
  tenantAccessToken?: string;
  /** Short alias for accessToken. */
  token?: string;
  /** Base URL, useful for a proxy or a mock server. */
  baseUrl?: string;
  /** Injected fetch implementation; defaults to globalThis.fetch. */
  fetch?: FetchLike;
  /** Additional headers sent with every request. */
  headers?: Record<string, string>;
  /** Optional AbortSignal applied to every request. */
  signal?: AbortSignal;
}

export interface TenantAccessTokenOptions extends RetryOptions {
  appId: string;
  appSecret: string;
  baseUrl?: string;
  fetch?: FetchLike;
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export interface FetchResponseLike {
  readonly ok?: boolean;
  readonly status: number;
  readonly statusText?: string;
  readonly headers?: HeadersLike;
  json(): Promise<unknown>;
  text?(): Promise<string>;
}

export interface HeadersLike {
  get(name: string): string | null;
}

export type FetchLike = (
  input: string | URL,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
    signal?: AbortSignal;
  },
) => Promise<FetchResponseLike>;

export interface FeishuRequestOptions {
  /** Disable retries for this request. */
  noRetry?: boolean;
  /** Number of retries for this request, overriding client defaults. */
  maxRetries?: number;
  signal?: AbortSignal;
}

export interface SyncKeyConfig {
  /** Source column used to identify a row. */
  source?: string;
  /** Target Bitable field. Defaults to the mapped target for `source`. */
  target?: string;
  /** JSON configuration aliases. */
  sourceField?: string;
  targetField?: string;
}

export type SyncKey = string | SyncKeyConfig;

export interface SyncConfig {
  appToken: string;
  tableId: string;
  mappings: FieldMappingInput[];
  /** `upsert` by default; `append` only creates records. */
  mode?: 'upsert' | 'append';
  /** A source field name or source/target key definition for upsert. */
  uniqueKey?: SyncKey;
  /** Alias for uniqueKey used by some integrations. */
  key?: SyncKey;
  /** Maximum records per API request. Feishu allows at most 500. */
  batchSize?: number;
  /** Page size while reading existing records. */
  pageSize?: number;
  /** If true, rows without a key are skipped; otherwise they fail. */
  skipInvalidRows?: boolean;
  /** Continue processing other batches after an API batch failure. */
  continueOnError?: boolean;
  /** Do not mutate Feishu; still map and classify rows. */
  dryRun?: boolean;
  /** Called after each successful create/update batch. */
  onProgress?: (progress: SyncProgress) => void | Promise<void>;
}

export interface SyncProgress {
  operation: 'create' | 'update';
  batchIndex: number;
  batchCount: number;
  records: number;
}

export interface SyncError {
  operation: 'map' | 'create' | 'update';
  message: string;
  rowIndex?: number;
  cause?: unknown;
}

export interface SyncResult {
  mode: 'upsert' | 'append';
  totalRows: number;
  mappedRows: number;
  created: number;
  updated: number;
  skipped: number;
  errors: SyncError[];
}

export interface FeishuClientLike {
  requestData?<T = unknown>(
    method: string,
    path: string,
    body?: unknown,
    options?: FeishuRequestOptions,
  ): Promise<T>;
  listTables?(
    appToken: string,
    options?: { pageSize?: number; pageToken?: string; signal?: AbortSignal },
  ): Promise<{ items: FeishuTable[]; hasMore: boolean; pageToken?: string; total?: number }>;
  listAllTables?(
    appToken: string,
    options?: { pageSize?: number; signal?: AbortSignal },
  ): Promise<FeishuTable[]>;
  listFields?(
    appToken: string,
    tableId: string,
    options?: { pageSize?: number; pageToken?: string; signal?: AbortSignal },
  ): Promise<{ items: FeishuField[]; hasMore: boolean; pageToken?: string; total?: number }>;
  listAllFields?(
    appToken: string,
    tableId: string,
    options?: { pageSize?: number; signal?: AbortSignal },
  ): Promise<FeishuField[]>;
  listRecords?(
    appToken: string,
    tableId: string,
    options?: RecordSearchOptions,
  ): Promise<FeishuRecordPage>;
  listAllRecords?(
    appToken: string,
    tableId: string,
    options?: RecordSearchOptions,
  ): Promise<FeishuRecord[]>;
  searchRecords?(
    appToken: string,
    tableId: string,
    options?: RecordSearchOptions,
  ): Promise<FeishuRecordPage>;
  batchCreateRecords(
    appToken: string,
    tableId: string,
    records: FeishuCreateRecordInput[],
    options?: { batchSize?: number; signal?: AbortSignal },
  ): Promise<FeishuBatchResult[]>;
  batchUpdateRecords(
    appToken: string,
    tableId: string,
    records: FeishuUpdateRecordInput[],
    options?: { batchSize?: number; signal?: AbortSignal },
  ): Promise<FeishuBatchResult[]>;
}

export class MappingError extends Error {
  readonly rowIndex?: number;
  readonly source?: string;

  constructor(message: string, options: { rowIndex?: number; source?: string; cause?: unknown } = {}) {
    super(message);
    this.name = 'MappingError';
    this.rowIndex = options.rowIndex;
    this.source = options.source;
    if (options.cause !== undefined) {
      (this as Error & { cause?: unknown }).cause = options.cause;
    }
  }
}

export class FeishuApiError extends Error {
  readonly status?: number;
  readonly code?: number | string;
  readonly requestId?: string;
  readonly response?: unknown;
  readonly retryable: boolean;

  constructor(
    message: string,
    options: {
      status?: number;
      code?: number | string;
      requestId?: string;
      response?: unknown;
      retryable?: boolean;
      cause?: unknown;
    } = {},
  ) {
    super(message);
    this.name = 'FeishuApiError';
    this.status = options.status;
    this.code = options.code;
    this.requestId = options.requestId;
    this.response = options.response;
    this.retryable = options.retryable ?? false;
    // `cause` is not available in every TypeScript lib target, so assign it
    // without making it a required compile-time property.
    if (options.cause !== undefined) {
      (this as Error & { cause?: unknown }).cause = options.cause;
    }
  }
}
